# Generated by Django 5.2.2 on 2025-06-11 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='id',
        ),
        migrations.AlterField(
            model_name='book',
            name='gutenberg_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
